### ISSUE TITLE
Responsive setting: equal-height

### ISSUE THREAD

**Issue by juergen1964** [typo3-themes/theme_bootstrap4#11]
Hello and thanks for working on theme_bootstrap4!

I got a problem with  the responsive settings: equal-height.

equal-height is by default selected in the settings of a gridelements contentelement (2ColumnGrid 3ColumnGrid and 4ColumnGrid) - this works fine so far, If i set the colum-width of a Gridelement (for example the 2-colum grid / large desktops) to 12 - 12 the 2nd colum will not move under the 1st colum like it should by using 12 -12 - it showes up beside the 1st colum and ruin the layout.

with grid settings 6 - 6, 9 - 3 and so on, everything works like it should. 

Is there a adjustment i need to add for the equal height setup to change the behavior different if a 12-12 setup is used (maybe change the flex-direction:row to flex-direction:column;) ?
by change the fex-direction to "column" the 2nd colum move unter the 1st colum (of course) but how to use a condition to check if the setting 12 - 12 is used.  Any ideas?

and - i am sorry - i dont`t understand the code of the equal-height.scss (Resources/Private/Dyncss/Library/Behaviour/ equal-height.scss):

for example the xl: 
```
.xl-eq-height {
	@include theme-media-breakpoint-only(xl) {
		@if$enable-flex == false {
			.row, .row > div[class*='col-'] {
				display: -webkit-box;
				display: -webkit-flex;
				display: flex;
				flex: 1 0 auto;
			}
		}
	}
}
```
... i also tryed to set $enable-flex == false to true - and maybe it would be better to set the responsive setting by default to: no equal-height so if i need equal-height i can select it.

an i think this behaviour is more complex with the 3ColumnGrid and 4ColumnGrid of the Gridelements with settings of 6-6-2 12-6-6 12-12-12 ... and so on - I hope my problem-description is understandable and somebody could help with a solution ? Anyway thanks for reading this!

**Comment by kaystrobach** [comment]
please post screenshots of your settings and your result + the expected result - thank you

**Comment by juergen1964** [comment]
thanks for your answer - here are the screenshots - i hope this is all you wanted
![8-4-equal-height](https://user-images.githubusercontent.com/22134047/27541923-06f2ab46-5a86-11e7-9f79-c8bf36ab5eec.png)
![eq-12-12](https://user-images.githubusercontent.com/22134047/27541924-06f495c8-5a86-11e7-8905-37d08cd89a89.png)
![no-equal-height-12-12](https://user-images.githubusercontent.com/22134047/27541927-07079e70-5a86-11e7-87ba-0ee3ac29bfab.png)
![settings-8-4-equal](https://user-images.githubusercontent.com/22134047/27541925-07030220-5a86-11e7-8dfa-892abebb3564.png)
![settings-12-12-equale](https://user-images.githubusercontent.com/22134047/27541926-07062432-5a86-11e7-80df-a8d79bd944dd.png)

**Comment by juergen1964** [comment]
Hi kaystrobach,
can You confirm this behaviour or did i something wrong?

Thx and have a nice day!

**Comment by kaystrobach** [comment]
seems to be valid, maybe @tdeuling can take a look into it.

**Comment by dbruening** [comment]
Hello, 

the equal-height settings are at the moment not realy complete. Bootstrap changed some (a lot of) settings in the next alpha version also. They use always felxbox for the grids.

The best way ist to enabled felxbox globally (Constant: themes.configuration.bootstrap.options.enableFlex = true). In order to allow the element lying inside to grow try the following CSS:

`        .row > div[class*='col-'] > * {
            height: 100%;
        }
`

**Comment by juergen1964** [comment]
Hello Mr. dbruening,

thx for your helping hand!

I tryed the given Css and it looks like it will work out so far - the gridelements work now like expected - as far i can tell after a quick testing. 

But unfortunatly enable flexbox globally (or something else - maybe the given Css?) ruin my layout and cause other problems - i need to investigate that after i am done setting up my website completely. 

After that i will come back to that equal-height issue and do more testing. I will post my results here and let You know what i found out or what i dont found out :-)

thx and have a nice weekend.

**Comment by juergen1964** [comment]
Hello Mr. dbruening,

today i tryed to make the equal height settings to work like i need it.

Here what i found out:
I turned on flexbox globaly (typoscript constants: enableFlex=true)

Your code:
.row > div[class*='col-'] > * { height: 100%; }
this work fine with the gridelements and the result looks like expected - but it ruins my layout and cause problems for example with my main-navigation and also with my news-list-templates. Probably because Your given code got effect on all ".row" classes.

so i tryed to use the code only on all ".xl-eq-height" ".lg-eq-height" "md-eq-height" and so on -  classes

like this:
.xl-eq-height .row > div[class*='col-'] > * { height: 100%; }
.lg-eq-height .row > div[class*='col-'] > * { height: 100%; }
...same for md, sm and xs

than it works fine so far.

and adding a margin when there is used for example 12 : 6 : 6 on the responsive settings make it look ok.  Like this:
.xl-eq-height .column-first { margin-bottom:15px; }
.xl-eq-height .column-middle { margin-bottom:15px; }
.xl-eq-height .column-last { margin-bottom:15px; }

this solved a few problems (of course) with ruin my layout on different parts - but it looks like to enable flexbox globaly got also effect on all given ".container" classes. So i still got some issues with my layout. And i dont have any clue how to fix this properly.

And after all i am really not sure what effect of some other parts of the coding my changes will have. I dont got enough knowledge on this. 

Sadly but better i don`t use the equal-height feature  for now.   Or you got any idea?

Thx for the helping hand

**Comment by juergen1964** [comment]
hu - i closed this issue sorry
