### ISSUE TITLE
Update Bootstrap 4 Beta planned?

### ISSUE THREAD

**Issue by juergen1964** [typo3-themes/theme_bootstrap4#15]
Hi there,
is it planned to use the Beta 4 Version in the future? Tryed myself to update it and get it work. I thought this should not be a big deael, just change the Bootstrap4 source in the Contrib direction and ajust a few classes in the templates - but i get sass errors (exaple: Undefined mixin _assert-ascending: line: 165).

I understand that i need to define the mixin _assert-ascending but what would be the right value. And even if i define a value the error disapear of course and next missing message show up. 

I guess there are a few adjustments on different parts necessary to run it with the Beta. 
Did anybody also tryed the Beta an did it get running?
Thx for every information.

**Comment by kaystrobach** [comment]
Please provide PR if you already did hal of the journey. Then someone may take a look.

Thank you.

**Comment by juergen1964** [comment]
Hi kaystrobach, 
thx for the quick replay - sorry my english seems not good enough to understand your answer properly. 

Please provide PR (?) if you already did hal of the journey - means this i should set up the beta update and someone (maybe You) will take a look if i give you the link to the website? That would be very nice! 

Thank You!

**Comment by kaystrobach** [comment]
PR means Pull Request.

Basicly it means, that you can send us your proposed changes and we will review them and may include them if they are ok.

Bedeutet, dass du uns deine Änderungen schickst und wir die dann prüfen und ggf. direkt in das Repo übernehmen.

Siehe auch: http://praxistipps.chip.de/github-pull-request-so-wirds-gemacht_49277

**Comment by juergen1964** [comment]
Ok - after all i startet once more to get the update to Bootstrap4 Beta2 work. 
And after all, now it looks not so bad so far - no sass errors anymore! 

What i did:

Because i delete all of the js files in my typoscript setup first and than load the .js files manually i needed to make some changes in loading the .js files.
At first i removed the tether.js from the Alpha version  (no need for that file in Beta version) 
Then i added the bootstrap.bundle.js (new in Beta Version) and the bootstrap.min.js  from the Bootstrap Beta2 folder ( dist/js) folder). 
I used before the bootstrap.min.js form the Alpa version, but i am not sure if the files are different (did not checked that so far). Anyway i use now the beta2 bootstrap.min.js from the Beta2 Version.

Next step was just to import only the Bootstrap4 Beta2 .scss files without my custom import files. Now everything worked without any errors. 

I think important was the right order of loading the files.
my import.scss starts with this imports:

// Be sure that all Bootstrap variables are defined!
@import "../../Public/Contrib/Bootstrap/scss/functions.scss";
@import "../../Public/Contrib/Bootstrap/scss/variables.scss"; 

@import "Library/Variables/font-family-sans-serif.scss";
@import "Library/Variables/font-family-serif.scss";
@import "Library/Variables/font-family-monospace.scss";
@import "Library/Variables/theme.scss";

// Mixins
@import "Library/Mixins/font-include.scss";
@import "Library/Mixins/breakpoints.scss";
@import "Library/Mixins/theme-mixins.scss";

// Scss-Imports
@import "Library/bootstrap.scss";

....

...the functions.scss is one of the new files in the Beta2 and import that file in the first line made the error "Undefined mixin _assert-ascending: line: 165" disapear.

After that i added my custom imports step by step to see if there are some errors depend on my custum files. I got two more errors and i will investigate that and will fix that. But so far it looks like the Bootstrap4 Beta is running now without errors!

The layout, navbar and some classes i need to adjust now too, cause of some new classes, renamed classes and stuff in the Beta2 ruin the layout like expected. I think this will take a bit time to fix but i hope this should not be a big problem.

Thx so far for lend a helping hand.

I hope

**Comment by dbruening** [comment]
Please have a look at the rebase branch, this branch contains bootstrap 4 beta.
We are working in this separate branch because of many breaking changes.

Also note that you no longer need themes_gridelements. The corresponding functions have been integrated in the theme_bootstrap4 (rebase).

**Comment by pniederlag** [comment]
btw. theme_bootstrap4 meanwhile ships bootstrap 4.1.0 stable so this issue can safely be closed with state DONE. ;)
