### ISSUE TITLE
Please move bootstrap variables overrides to TS

### ISSUE THREAD

**Issue by fazzyx** [typo3-themes/theme_bootstrap4#4]
Hi @dbruening,

after the last update I get in trouble with bootstrap variables definition in your theme.scss.
In detail, I'm using the variable $enable-flex in my custom theme which depends on theme_bootstrap4.
theme_bootstrap4 set the variable to false (btw. this is the bs4 default atm.)
My theme set this variable to true, but this is not working anymore.
It looks like that the reason for this is the scss parser.
I've already discussed this with @kaystrobach at slack, see 
https://typo3.slack.com/archives/typo3-themes/p1476364140000031
It would be nice if u can move the bs variables definition to TS.
Than other themes would be able to override this.

Thank You!

**Comment by dbruening** [comment]
Hi @fazzyx,

thanks for your report!

I've reomove the option variables from theme_bootstrap4.

Now the bootstrap options can be used by DynCss overrides.
There are some of the options avalible in the backend themes module.

The options that are required to develop the theme and do not affect the appearance are not avalible by the module. But you can set them over the constants.

In your case, you need this one:
themes.configuration.bootstrap.options.enableFlex = true

**Comment by fazzyx** [comment]
Great! Thank you very much @dbruening!
