### ISSUE TITLE
Please add tags on git

### ISSUE THREAD

**Issue by pniederlag** [typo3-themes/theme_bootstrap4#84]
Please add some tags on git so composer based installs can use this package without dealing with constant updates on master.

I have created a fork and added tags 0.5.1, 0.6.0, 0.8.0 and 0.9.0
https://github.com/datenbetrieb/theme_bootstrap4

```
git remote add fork git@github.com:datenbetrieb/theme_bootstrap4
git fetch --all
git tag -ln1
# if you agree
# git push origin --tags
```

**Comment by kaystrobach** [comment]
@tdeuling that's ok for me, and maybe we should also add branches starting from those tags for later bugfixes.

So if you agree i would add the tags ... if not please tell me until friday. Thank you.

**Comment by tdeuling** [comment]
@kaystrobach It's ok.

**Comment by kaystrobach** [comment]
tags done

**Comment by kaystrobach** [comment]
branches done

**Comment by kaystrobach** [comment]
@pniederlag I will close the ticket, was we have branches and tags now.

@tdeuling having semver will make live easier for you as well, as there is no need for backporting features anymore.
